server:
  command: "php public/website.php"
  env:
    - APP_RUNTIME: Runtime\RoadRunnerSymfonyNyholm\Runtime

logs:
  mode: production
  level: debug

  channels:
    http:
      level: info
    server:
      level: info
    rpc:
      level: debug

http:
  address: 127.0.0.1:8080
  middleware: ["headers", "static", "gzip"]
  uploads:
    forbid: [".php", ".exe", ".bat", ".sh"]
  static:
    dir: "public"
    forbid: [".htaccess"]
  headers:
    response:
      X-Powered-By: "RoadRunner"
  pool:
    num_workers: 2

status:
  address: 127.0.0.1:2114

